### ISSUE TITLE
Assigning a new maintainer?

### ISSUE THREAD

**Issue by x3ro** [nthloop/Objektiv#10]
It seems like Objektiv is no longer being actively maintained. While it still works on current versions of OS X, there are some annoying bugs (#4, #5, #7) which somewhat impact UX. I've tried to contact @Anks and @xrivatsan via Twitter, but there hasn't been a response so far.

Are you folks up for assigning a new maintainer to the project? I'd hate to have to fork under a new name, but it'd be nice to have a properly working version of Objektiv again :)

**Comment by x3ro** [comment]
Ping @Anks and @xrivatsan once more :game_die:

**Comment by adamcstephens** [comment]
I'm interested in a version that fixes the outstanding issues, if it becomes available.

**Comment by x3ro** [comment]
I did write an experimental fix for the "icon does not change" problem, available [here](https://github.com/nthloop/Objektiv/compare/master...x3ro:wip)

**Comment by Vorror** [comment]
If anyone still cares, I forked the project and made various fixes:
- Activating shortcut again closes window
- Center preferences on first launch + Remember preference window location between launches
- Ability to turn off Notifications
- Shorten notification message
- Fix issue with dedicated graphic cards
- Fix issue with default browser selection
- Fix issue with overlay when the number of browsers is divisible by 9

I haven't made a binary build yet.

**Comment by cmeury** [comment]
I have been added as a new maintainer and will work with @Vorror to get his fixes upstream, and release a new binary.

**Comment by x3ro** [comment]
Nice! 🎉
