### ISSUE TITLE
Install Objektiv with Homebrew

### ISSUE THREAD

**Issue by xuv** [nthloop/Objektiv#16]
Love this app. It's really useful. Would be great to be able to install it with Homebrew.

**Comment by cmeury** [comment]
I'm trying to get it included in `homebrew-casks` with now the official repository as a source: https://github.com/Homebrew/homebrew-cask/pull/82675

**Comment by cmeury** [comment]
Objektiv can now be installed via homebrew:

    brew cask install objektiv

Will also update the documentation.

**Comment by xuv** [comment]
Congratulations and thank you for bringing so many people together to make this happen. Thank you to the Objektiv community.

**Comment by xuv** [comment]
Installed via Homebrew, so closing this issue :)
