### ISSUE TITLE
Objektiv kicks on discrete graphics when the overlay is used

### ISSUE THREAD

**Issue by hawkrives** [nthloop/Objektiv#5]
Whenever I trigger Objektiv's overlay via the keyboard shortcut, my retina mbp switches over to the discrete card and refuses to switch back until I quit Objektiv.

I have no ideas as to why.

**Comment by Vorror** [comment]
Fixed with: https://github.com/Vorror/Objektiv/releases Also gave you credit.

**Comment by cmeury** [comment]
Fixed with #17
