### ISSUE TITLE
Feature request: Turn off confirmation dialog

### ISSUE THREAD

**Issue by edmechem** [nthloop/Objektiv#8]
Great little utility!   One thing that would make it even better, would be the option to turn off the confirmation dialog.  I just want it to work, fast, and then get out of my way.  Confirming, what I've already just told it to do, is one more extra step that feels like unnecessary friction.  I understand some users might want this, but please provide the option to turn it off!  Thanks.
![objektivconfirmationdialog](https://cloud.githubusercontent.com/assets/171138/11165974/07b00f5a-8ad6-11e5-8e0d-85ee439e88e8.jpg)

**Comment by Vorror** [comment]
I made a fork. Should be fixed with: https://github.com/Vorror/Objektiv/releases

**Comment by nerdo** [comment]
Genius of you to make Objectiv a browser, and essentially proxy the requests through it!

Now using it feels seamless!

**Comment by cmeury** [comment]
Fixed with #17
