### ISSUE TITLE
Bug: Icon in menu doesn't update until clicked

### ISSUE THREAD

**Issue by edmechem** [nthloop/Objektiv#9]
When I change my default browser, the menubar icon (nor the checked item in the menu) doesn't change -- until I click the icon.  After clicking, the icon changes to the correct browser, and when I click again, the correct browser is checked.  But at first, it's not checked - the previously selected browser is.

The actual default browser _does_ switch - it's just the menu icon that doesn't update, until I click on it.

(  I realize I could just turn it off, but it does provide useful at-a-glance feedback about which browser I've got currently selected as my default - or, would - if it worked. )

**Comment by natan** [comment]
Fixed by https://github.com/nthloop/Objektiv/issues/9.

**Comment by Vorror** [comment]
@cmeury I don't think this ticket is necessary since Objektiv is a "browser" itself and doesn't change the default browser anymore. I suspect this can be closed.

**Comment by cmeury** [comment]
Thanks, Vorror. Closing this one.
